# Generated by Django 5.2.8 on 2026-02-18 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_active_project_per_owner',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner', 'name'), name='unique_active_project_per_owner'),
        ),
    ]
