# Generated by Django 5.2.8 on 2026-03-11 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_unique_active_project_per_owner_and_more'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_active_project_per_owner',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_owner_i_c299b3_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='workspace.workspace'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace'], name='projects_workspa_317e49_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace', 'name'), name='unique_active_project_per_workspace'),
        ),
    ]
