# Generated by Django 5.2.8 on 2026-03-17 15:02

from django.db import migrations


def migrate_is_completed_to_status(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    # 3 is DONE in our Status choices
    Task.objects.filter(is_completed=True).update(status=3)
    # 1 is TODO in our Status choices
    Task.objects.filter(is_completed=False).update(status=1)

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_is_completed_to_status),
    ]
