# Generated by Django 5.2.8 on 2026-03-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_migrate_is_completed_to_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
