# Generated by Django 5.2.8 on 2026-03-20 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0003_remove_project_unique_active_project_per_owner_and_more'),
        ('workspace', '0004_workspaceinvitation_unique_pending_invitation_per_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='AuditLog',
        ),
    ]
